# Generated by Django 3.0.2 on 2020-03-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=7)),
                ('real_name', models.CharField(max_length=7)),
                ('tz', models.CharField(max_length=10)),
            ],
        ),
    ]
